baseURL = "https://omanshuthapliyal.github.io/"

# set your your own ga token here.
googleAnalytics = "UA/G-1GN9J4R0RF"

languageCode = "en-us"

# for using avicenna you need to set the themes to 'avicenna'
enableEmoji = true
theme = "avicenna"

# This is your page title, it appears in your tab
title = "Omanshu Thapliyal"

# number of posts to show on the blog page
pagination.pagerSize = 5
  
[markup]

  [markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 1

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['$$', '$$']]


[params]
# it is used for the copy-right section of your page
name = "Omanshu Thapliyal"
math = true
